coverage:
  precision: 2
  round: up
  range: 50...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project:
      default:
        target: auto
        threshold: 1%
    patch: true
    changes: false

comment:
  layout: "header, diff, tree"
  behavior: default  # update if exists else create new
